# Updating an old model with new features
Old X patients (age, sex, complaint) → base model. Later, X new patients with vitals V1–V3. Three ways to add the vitals, compared on the same test set.

## 1. Data
Old batch, new batch and test set, all from the same simulated population.

### 1.1 Setup

In [1]:
import os

# must be set before pymc/jax are imported
os.environ["JAX_PLATFORMS"] = "cpu"                                     # GPU was slower for this model
os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=6"    # one JAX device per chain, run in parallel

import numpy as np
import pandas as pd
import pymc as pm

SEED = 42

### 1.2 Patients

In [2]:
rng = np.random.default_rng(SEED)
N_OLD, N_NEW, N_TEST = 20_000, 20_000, 20_000
N = N_OLD + N_NEW + N_TEST
COMPLAINTS = ["chest pain", "shortness of breath", "headache", "abdominal pain"]

df = pd.DataFrame({
    "age": rng.normal(55, 18, N).clip(18, 100).round(),
    "male": rng.binomial(1, 0.5, N),
    "complaint": rng.choice(COMPLAINTS, N),
})
# vital signs, shaped after the real ED patients in data.csv.xls
# the old patients have vitals too (they drive their risk), but no model is ever shown them
fever = rng.random(N) < 0.10                      # 10% febrile
cold = rng.random(N) < 0.005                      # 0.5% hypothermic
V1 = rng.normal(36.55, 0.4, N) + fever * rng.gamma(2.0, 0.6, N)
df["V1"] = np.where(cold, rng.normal(34.6, 0.6, N), V1).clip(30, 42.5).round(1)                   # body temperature, °C
df["V2"] = (rng.lognormal(np.log(131), 0.2, N) + 0.4 * (df["age"] - 55)).clip(50, 260).round()     # systolic BP, mmHg
df["V3"] = (rng.lognormal(np.log(82), 0.21, N) + 10 * (df["V1"] - 36.6)).clip(30, 220).round()    # heart rate, bpm

# old: the first records, used once for the base model and then gone; new: arrive later with vitals; test: held out
df["group"] = np.repeat(["old", "new", "test"], [N_OLD, N_NEW, N_TEST])
in_old, in_new, in_test = (df["group"] == g for g in ["old", "new", "test"])
df.head()

    age  male            complaint    V1     V2    V3 group
0  60.0     1           chest pain  36.5  115.0  88.0   old
1  36.0     0       abdominal pain  36.1  118.0  87.0   old
2  69.0     1  shortness of breath  36.0  120.0  58.0   old
3  72.0     1       abdominal pain  36.7  166.0  71.0   old
4  20.0     1             headache  36.1  112.0  70.0   old

### 1.3 Features

In [3]:
# age is scaled with the old batch, as the base model was built on it; vitals with the new batch, where they first appear
AGE_MEAN, AGE_SD = df.loc[in_old, "age"].mean(), df.loc[in_old, "age"].std()
VITALS = ["V1", "V2", "V3"]
VITAL_MEAN, VITAL_SD = df.loc[in_new, VITALS].mean(), df.loc[in_new, VITALS].std()

X = pd.DataFrame({
    "age": (df["age"] - AGE_MEAN) / AGE_SD,
    "male": df["male"],
})
for c in COMPLAINTS[1:]:
    X[c] = (df["complaint"] == c).astype(int)
# each vital: a standardised linear term plus its square, so both low and high values can raise risk
for v in VITALS:
    z = (df[v] - VITAL_MEAN[v]) / VITAL_SD[v]
    X[v] = z
    X[v + "_sq"] = z ** 2

BASE_COLS = ["age", "male"] + COMPLAINTS[1:]
VITAL_COLS = [c for v in VITALS for c in (v, v + "_sq")]
ALL_COLS = BASE_COLS + VITAL_COLS
X.head()

,age,male,shortness of breath,headache,abdominal pain,V1,V1_sq,V2,V2_sq,V3,V3_sq
0,0.272484,1,0,0,0,-0.252569,0.063791,-0.670029,0.448939,0.190036,0.036114
1,-1.086172,0,0,0,1,-0.903645,0.816575,-0.563192,0.317186,0.137386,0.018875
2,0.781980,1,1,0,0,-1.066414,1.137239,-0.491968,0.242032,-1.389471,1.930630
3,0.951812,1,0,0,1,0.072969,0.005325,1.146198,1.313769,-0.705018,0.497051
4,-1.991943,1,0,1,0,-0.903645,0.816575,-0.776866,0.603521,-0.757668,0.574061

### 1.4 True model and deaths

In [4]:
# the true values, used to simulate deaths and to score the models
rng = np.random.default_rng(SEED)
TRUE_INTERCEPT = -4.2           # keeps mortality near 3% with the vitals added
TRUE_BETA = pd.Series({
    "age": 0.8,                   # per standard deviation of age (about 18 years)
    "male": 0.3,
    "shortness of breath": 0.5,
    "headache": -0.7,
    "abdominal pain": -0.2,
    # vitals, per standard deviation (linear) and per squared standard deviation (curvature)
    "V1": 0.1,   "V1_sq": 0.04,     # temperature: long fever tail, so a small square term
    "V2": -0.3,  "V2_sq": 0.1,      # systolic BP: low is worse than high
    "V3": 0.2,   "V3_sq": 0.1,      # heart rate
})

p_true = 1 / (1 + np.exp(-(TRUE_INTERCEPT + X[ALL_COLS] @ TRUE_BETA)))
df["dead"] = rng.binomial(1, p_true)
df.groupby("group", sort=False)["dead"].agg(patients="size", deaths="sum", rate="mean")

       patients  deaths     rate
group
old       20000     626  0.03130
new       20000     634  0.03170
test      20000     569  0.02845

## 2. Base model
Fitted once on the old X K: age, sex and complaint, N(0, 1) priors.

### 2.1 Fit
$x_i$ = base features (age, sex, complaint), $y_i$ = 1 if patient $i$ died.

$$\operatorname{logit} p_i = \alpha + x_i^\top \beta, \qquad y_i \sim \text{Bernoulli}(p_i), \qquad \alpha,\ \beta_j \sim \mathcal{N}(0, 1)$$

$$p(\alpha, \beta \mid D_\text{old}) \;\propto\; \prod_{i \in \text{old}} p_i^{y_i} (1 - p_i)^{1 - y_i} \;\cdot\; \mathcal{N}(\alpha; 0, 1) \prod_j \mathcal{N}(\beta_j; 0, 1)$$

In [5]:
with pm.Model(coords={"feature": BASE_COLS}) as model_base:
    intercept = pm.Normal("intercept", mu=0, sigma=1)
    beta = pm.Normal("beta", mu=0, sigma=1, dims="feature")

    pm.Bernoulli("dead", logit_p=intercept + pm.math.dot(X.loc[in_old, BASE_COLS].values, beta),
                 observed=df.loc[in_old, "dead"].values)

    # 6 chains x 667 draws ≈ 4000 draws, sampled with NumPyro (JAX) on the CPU
    idata_base = pm.sample(667, tune=1000, chains=6, nuts_sampler="numpyro", random_seed=SEED)

NUTS[numpyro]: [intercept, beta]

/home/theo/Work/DEV/skola/pda/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 0:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 1:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 2:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 3:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 4:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 5:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 0:   5%|▍         | 83/1667 [00:01<00:12, 125.29it/s]

Running chain 5:   5%|▍         | 83/1667 [00:01<00:13, 118.84it/s]

Running chain 4:   5%|▍         | 83/1667 [00:01<00:13, 118.46it/s]

Running chain 3:   5%|▍         | 83/1667 [00:01<00:13, 115.10it/s]

Running chain 1:   5%|▍         | 83/1667 [00:01<00:14, 111.12it/s]

Running chain 2:   5%|▍         | 83/1667 [00:02<00:15, 103.28it/s]

Running chain 1:  10%|▉         | 166/1667 [00:02<00:12, 121.75it/s]

Running chain 0:  10%|▉         | 166/1667 [00:02<00:12, 116.45it/s]

Running chain 3:  10%|▉         | 166/1667 [00:02<00:13, 109.60it/s]

Running chain 5:  10%|▉         | 166/1667 [00:02<00:13, 108.19it/s]

Running chain 4:  10%|▉         | 166/1667 [00:02<00:14, 101.07it/s]

Running chain 2:  10%|▉         | 166/1667 [00:02<00:15, 99.74it/s]

Running chain 1:  15%|█▍        | 249/1667 [00:03<00:10, 132.23it/s]

Running chain 0:  15%|█▍        | 249/1667 [00:03<00:12, 116.73it/s]

Running chain 3:  15%|█▍        | 249/1667 [00:03<00:12, 117.58it/s]

Running chain 5:  15%|█▍        | 249/1667 [00:03<00:13, 107.58it/s]

Running chain 2:  15%|█▍        | 249/1667 [00:03<00:13, 109.07it/s]

Running chain 4:  15%|█▍        | 249/1667 [00:03<00:14, 94.85it/s]

Running chain 1:  20%|█▉        | 332/1667 [00:03<00:10, 121.82it/s]

Running chain 3:  20%|█▉        | 332/1667 [00:04<00:11, 115.21it/s]

Running chain 5:  20%|█▉        | 332/1667 [00:04<00:11, 116.77it/s]

Running chain 0:  20%|█▉        | 332/1667 [00:04<00:12, 111.21it/s]

Running chain 2:  20%|█▉        | 332/1667 [00:04<00:11, 113.65it/s]

Running chain 4:  20%|█▉        | 332/1667 [00:04<00:13, 101.86it/s]

Running chain 1:  25%|██▍       | 415/1667 [00:04<00:09, 129.48it/s]

Running chain 3:  25%|██▍       | 415/1667 [00:04<00:09, 129.39it/s]

Running chain 5:  25%|██▍       | 415/1667 [00:04<00:10, 124.67it/s]

Running chain 2:  25%|██▍       | 415/1667 [00:04<00:09, 126.93it/s]

Running chain 0:  25%|██▍       | 415/1667 [00:04<00:10, 116.53it/s]

Running chain 4:  25%|██▍       | 415/1667 [00:05<00:11, 109.34it/s]

Running chain 1:  30%|██▉       | 498/1667 [00:05<00:09, 127.43it/s]

Running chain 5:  30%|██▉       | 498/1667 [00:05<00:08, 130.00it/s]

Running chain 3:  30%|██▉       | 498/1667 [00:05<00:09, 125.06it/s]

Running chain 0:  30%|██▉       | 498/1667 [00:05<00:09, 119.22it/s]

Running chain 2:  30%|██▉       | 498/1667 [00:05<00:09, 123.55it/s]

Running chain 1:  35%|███▍      | 581/1667 [00:05<00:08, 129.14it/s]

Running chain 4:  30%|██▉       | 498/1667 [00:05<00:10, 110.18it/s]

Running chain 5:  35%|███▍      | 581/1667 [00:05<00:08, 128.40it/s]

Running chain 3:  35%|███▍      | 581/1667 [00:06<00:08, 123.81it/s]

Running chain 0:  35%|███▍      | 581/1667 [00:06<00:09, 112.33it/s]

Running chain 2:  35%|███▍      | 581/1667 [00:06<00:09, 113.55it/s]

Running chain 1:  40%|███▉      | 664/1667 [00:06<00:08, 124.01it/s]

Running chain 5:  40%|███▉      | 664/1667 [00:06<00:07, 131.53it/s]

Running chain 3:  40%|███▉      | 664/1667 [00:06<00:07, 126.83it/s]

Running chain 4:  35%|███▍      | 581/1667 [00:06<00:09, 109.77it/s]

Running chain 0:  40%|███▉      | 664/1667 [00:06<00:07, 128.19it/s]

Running chain 2:  40%|███▉      | 664/1667 [00:06<00:07, 126.22it/s]

Running chain 1:  45%|████▍     | 747/1667 [00:07<00:06, 134.65it/s]

Running chain 5:  45%|████▍     | 747/1667 [00:07<00:06, 141.86it/s]

Running chain 3:  45%|████▍     | 747/1667 [00:07<00:06, 139.12it/s]

Running chain 4:  40%|███▉      | 664/1667 [00:07<00:08, 123.50it/s]

Running chain 0:  45%|████▍     | 747/1667 [00:07<00:06, 142.30it/s]

Running chain 2:  45%|████▍     | 747/1667 [00:07<00:06, 138.27it/s]

Running chain 5:  50%|████▉     | 830/1667 [00:07<00:05, 154.95it/s]

Running chain 1:  50%|████▉     | 830/1667 [00:07<00:05, 144.59it/s]

Running chain 3:  50%|████▉     | 830/1667 [00:07<00:05, 148.44it/s]

Running chain 4:  45%|████▍     | 747/1667 [00:07<00:06, 138.37it/s]

Running chain 0:  50%|████▉     | 830/1667 [00:07<00:05, 153.95it/s]

Running chain 2:  50%|████▉     | 830/1667 [00:07<00:05, 151.00it/s]

Running chain 5:  55%|█████▍    | 913/1667 [00:07<00:04, 164.86it/s]

Running chain 1:  55%|█████▍    | 913/1667 [00:08<00:04, 151.04it/s]

Running chain 3:  55%|█████▍    | 913/1667 [00:08<00:04, 157.33it/s]

Running chain 4:  50%|████▉     | 830/1667 [00:08<00:05, 149.25it/s]

Running chain 0:  55%|█████▍    | 913/1667 [00:08<00:04, 162.53it/s]

Running chain 2:  55%|█████▍    | 913/1667 [00:08<00:04, 160.10it/s]

Running chain 4:  55%|█████▍    | 913/1667 [00:08<00:04, 161.74it/s]

Running chain 5:  60%|█████▉    | 996/1667 [00:08<00:04, 153.29it/s]

Running chain 3:  60%|█████▉    | 996/1667 [00:08<00:04, 153.30it/s]

Running chain 1:  60%|█████▉    | 996/1667 [00:08<00:04, 145.10it/s]

Running chain 0:  60%|█████▉    | 996/1667 [00:08<00:04, 148.44it/s]

Running chain 2:  60%|█████▉    | 996/1667 [00:08<00:04, 151.25it/s]

Running chain 4:  60%|█████▉    | 996/1667 [00:09<00:04, 158.07it/s]

Running chain 5:  65%|██████▍   | 1079/1667 [00:09<00:04, 146.21it/s]

Running chain 1:  65%|██████▍   | 1079/1667 [00:09<00:04, 146.07it/s]

Running chain 3:  65%|██████▍   | 1079/1667 [00:09<00:04, 146.95it/s]

Running chain 0:  65%|██████▍   | 1079/1667 [00:09<00:03, 147.41it/s]

Running chain 2:  65%|██████▍   | 1079/1667 [00:09<00:03, 154.02it/s]

Running chain 4:  65%|██████▍   | 1079/1667 [00:09<00:03, 149.70it/s]

Running chain 1:  70%|██████▉   | 1162/1667 [00:09<00:03, 144.42it/s]

Running chain 5:  70%|██████▉   | 1162/1667 [00:09<00:03, 142.88it/s]

Running chain 3:  70%|██████▉   | 1162/1667 [00:09<00:03, 143.25it/s]

Running chain 2:  70%|██████▉   | 1162/1667 [00:09<00:03, 154.43it/s]

Running chain 0:  70%|██████▉   | 1162/1667 [00:09<00:03, 146.13it/s]

Running chain 4:  70%|██████▉   | 1162/1667 [00:10<00:03, 143.86it/s]

Running chain 1:  75%|███████▍  | 1245/1667 [00:10<00:02, 146.95it/s]

Running chain 2:  75%|███████▍  | 1245/1667 [00:10<00:02, 156.15it/s]

Running chain 5:  75%|███████▍  | 1245/1667 [00:10<00:02, 142.01it/s]

Running chain 3:  75%|███████▍  | 1245/1667 [00:10<00:02, 141.63it/s]

Running chain 0:  75%|███████▍  | 1245/1667 [00:10<00:02, 142.33it/s]

Running chain 2:  80%|███████▉  | 1328/1667 [00:10<00:02, 158.15it/s]

Running chain 1:  80%|███████▉  | 1328/1667 [00:10<00:02, 146.64it/s]

Running chain 4:  75%|███████▍  | 1245/1667 [00:10<00:02, 140.95it/s]

Running chain 5:  80%|███████▉  | 1328/1667 [00:10<00:02, 141.91it/s]

Running chain 3:  80%|███████▉  | 1328/1667 [00:11<00:02, 142.69it/s]

Running chain 0:  80%|███████▉  | 1328/1667 [00:11<00:02, 140.64it/s]

Running chain 2:  85%|████████▍ | 1411/1667 [00:11<00:01, 160.24it/s]

Running chain 1:  85%|████████▍ | 1411/1667 [00:11<00:01, 146.96it/s]

Running chain 4:  80%|███████▉  | 1328/1667 [00:11<00:02, 137.62it/s]

Running chain 5:  85%|████████▍ | 1411/1667 [00:11<00:01, 138.03it/s]

Running chain 3:  85%|████████▍ | 1411/1667 [00:11<00:01, 141.14it/s]

Running chain 0:  85%|████████▍ | 1411/1667 [00:11<00:01, 142.11it/s]

Running chain 2:  90%|████████▉ | 1494/1667 [00:11<00:01, 158.41it/s]

Running chain 1:  90%|████████▉ | 1494/1667 [00:12<00:01, 138.14it/s]

Running chain 4:  85%|████████▍ | 1411/1667 [00:12<00:01, 129.98it/s]

Running chain 5:  90%|████████▉ | 1494/1667 [00:12<00:01, 131.77it/s]

Running chain 3:  90%|████████▉ | 1494/1667 [00:12<00:01, 132.76it/s]

Running chain 0:  90%|████████▉ | 1494/1667 [00:12<00:01, 136.52it/s]

Running chain 2:  95%|█████████▍| 1577/1667 [00:12<00:00, 148.12it/s]

Running chain 1:  95%|█████████▍| 1577/1667 [00:12<00:00, 140.42it/s]

Running chain 4:  90%|████████▉ | 1494/1667 [00:12<00:01, 129.86it/s]

Running chain 3:  95%|█████████▍| 1577/1667 [00:12<00:00, 136.96it/s]

Running chain 0:  95%|█████████▍| 1577/1667 [00:12<00:00, 140.10it/s]

Running chain 5:  95%|█████████▍| 1577/1667 [00:12<00:00, 130.91it/s]

Running chain 2: 100%|█████████▉| 1660/1667 [00:13<00:00, 148.09it/s]

Running chain 2: 100%|██████████| 1667/1667 [00:13<00:00, 126.48it/s]

Running chain 1: 100%|█████████▉| 1660/1667 [00:13<00:00, 143.67it/s]

Running chain 1: 100%|██████████| 1667/1667 [00:13<00:00, 125.35it/s]

Running chain 0: 100%|█████████▉| 1660/1667 [00:13<00:00, 142.97it/s]

Running chain 3: 100%|█████████▉| 1660/1667 [00:13<00:00, 138.80it/s]

Running chain 4:  95%|█████████▍| 1577/1667 [00:13<00:00, 133.21it/s]

Running chain 5: 100%|█████████▉| 1660/1667 [00:13<00:00, 135.85it/s]

Running chain 0: 100%|██████████| 1667/1667 [00:13<00:00, 123.37it/s]

Running chain 3: 100%|██████████| 1667/1667 [00:13<00:00, 123.41it/s]

Running chain 5: 100%|██████████| 1667/1667 [00:13<00:00, 123.30it/s]

Running chain 4: 100%|█████████▉| 1660/1667 [00:13<00:00, 149.10it/s]

Running chain 4: 100%|██████████| 1667/1667 [00:13<00:00, 119.82it/s]

### 2.2 Base score
The base model as one fixed number per patient, using the posterior means $\bar\alpha, \bar\beta$:

$$s_i = \bar\alpha + x_i^\top \bar\beta$$

In [6]:
def draws_of(idata, cols, **fixed):
    """Posterior draws as a table: an intercept column and one per feature; `fixed` adds coefficients that are not sampled."""
    post = idata.posterior
    d = pd.DataFrame(post["beta"].values.reshape(-1, len(cols)), columns=cols)
    d.insert(0, "intercept", post["intercept"].values.ravel() if "intercept" in post else 0.0)
    return d.assign(**fixed)

base_draws = draws_of(idata_base, BASE_COLS)
# the base model as one fixed number per patient: its log-odds of death with the posterior-mean coefficients
X["base_lp"] = base_draws["intercept"].mean() + X[BASE_COLS] @ base_draws[BASE_COLS].mean()

pd.DataFrame({"true": pd.Series({"intercept": TRUE_INTERCEPT, **TRUE_BETA[BASE_COLS]}),
              "base mean": base_draws.mean(), "base sd": base_draws.std()}).round(2)

                     true  base mean  base sd
intercept            -4.2      -3.68     0.10
age                   0.8       0.73     0.04
male                  0.3       0.28     0.08
shortness of breath   0.5       0.41     0.10
headache             -0.7      -1.06     0.15
abdominal pain       -0.2      -0.43     0.12

## 3. Adding the vitals
Each method is fitted independently on the new 10K. The old patients are gone; only the base model is left.

### 3.1 Fixed base + vitals
Base score as a fixed offset; only the vital coefficients are learned. $v_i$ = vital features ($V1, V1^2, \dots, V3^2$).

$$\operatorname{logit} p_i = s_i + v_i^\top \gamma, \qquad \gamma_k \sim \mathcal{N}(0, 1)$$

$$p(\gamma \mid D_\text{new}) \;\propto\; \prod_{i \in \text{new}} p_i^{y_i} (1 - p_i)^{1 - y_i} \;\cdot\; \prod_k \mathcal{N}(\gamma_k; 0, 1)$$

In [7]:
y_new = df.loc[in_new, "dead"].values

with pm.Model(coords={"feature": VITAL_COLS}) as model_fixed:
    beta = pm.Normal("beta", mu=0, sigma=1, dims="feature")

    pm.Bernoulli("dead", logit_p=X.loc[in_new, "base_lp"].values + pm.math.dot(X.loc[in_new, VITAL_COLS].values, beta),
                 observed=y_new)

    idata_fixed = pm.sample(667, tune=1000, chains=6, nuts_sampler="numpyro", random_seed=SEED)

NUTS[numpyro]: [beta]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 0:   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 1:   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 2:   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 3:   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 4:   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 5:   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 1:   5%|▍         | 83/1667 [00:02<00:25, 62.75it/s]

Running chain 4:   5%|▍         | 83/1667 [00:02<00:25, 61.45it/s]

Running chain 0:   5%|▍         | 83/1667 [00:02<00:25, 61.04it/s]

Running chain 2:   5%|▍         | 83/1667 [00:02<00:26, 60.80it/s]

Running chain 3:   5%|▍         | 83/1667 [00:02<00:26, 59.32it/s]

Running chain 5:   5%|▍         | 83/1667 [00:02<00:27, 56.71it/s]

Running chain 5:  10%|▉         | 166/1667 [00:03<00:20, 72.54it/s]

Running chain 3:  10%|▉         | 166/1667 [00:03<00:21, 68.96it/s]

Running chain 0:  10%|▉         | 166/1667 [00:03<00:22, 65.95it/s]

Running chain 1:  10%|▉         | 166/1667 [00:03<00:23, 64.73it/s]

Running chain 2:  10%|▉         | 166/1667 [00:03<00:23, 63.41it/s]

Running chain 4:  10%|▉         | 166/1667 [00:03<00:24, 61.62it/s]

Running chain 5:  15%|█▍        | 249/1667 [00:03<00:15, 94.05it/s]

Running chain 3:  15%|█▍        | 249/1667 [00:04<00:15, 89.12it/s]

Running chain 0:  15%|█▍        | 249/1667 [00:04<00:16, 86.82it/s]

Running chain 1:  15%|█▍        | 249/1667 [00:04<00:17, 82.81it/s]

Running chain 2:  15%|█▍        | 249/1667 [00:04<00:16, 83.57it/s]

Running chain 4:  15%|█▍        | 249/1667 [00:04<00:16, 83.93it/s]

Running chain 5:  20%|█▉        | 332/1667 [00:04<00:12, 105.71it/s]

Running chain 0:  20%|█▉        | 332/1667 [00:04<00:13, 100.38it/s]

Running chain 3:  20%|█▉        | 332/1667 [00:04<00:13, 98.59it/s]

Running chain 4:  20%|█▉        | 332/1667 [00:04<00:13, 100.75it/s]

Running chain 1:  20%|█▉        | 332/1667 [00:04<00:13, 98.52it/s]

Running chain 2:  20%|█▉        | 332/1667 [00:04<00:13, 99.24it/s]

Running chain 5:  25%|██▍       | 415/1667 [00:05<00:10, 120.61it/s]

Running chain 0:  25%|██▍       | 415/1667 [00:05<00:10, 119.76it/s]

Running chain 2:  25%|██▍       | 415/1667 [00:05<00:10, 120.54it/s]

Running chain 3:  25%|██▍       | 415/1667 [00:05<00:10, 114.99it/s]

Running chain 1:  25%|██▍       | 415/1667 [00:05<00:10, 117.31it/s]

Running chain 4:  25%|██▍       | 415/1667 [00:05<00:10, 117.14it/s]

Running chain 5:  30%|██▉       | 498/1667 [00:05<00:08, 133.20it/s]

Running chain 0:  30%|██▉       | 498/1667 [00:05<00:09, 129.73it/s]

Running chain 2:  30%|██▉       | 498/1667 [00:05<00:09, 127.27it/s]

Running chain 4:  30%|██▉       | 498/1667 [00:05<00:09, 127.91it/s]

Running chain 1:  30%|██▉       | 498/1667 [00:05<00:09, 125.47it/s]

Running chain 3:  30%|██▉       | 498/1667 [00:05<00:09, 120.78it/s]

Running chain 5:  35%|███▍      | 581/1667 [00:06<00:07, 144.14it/s]

Running chain 0:  35%|███▍      | 581/1667 [00:06<00:07, 139.48it/s]

Running chain 4:  35%|███▍      | 581/1667 [00:06<00:07, 139.94it/s]

Running chain 2:  35%|███▍      | 581/1667 [00:06<00:07, 136.40it/s]

Running chain 3:  35%|███▍      | 581/1667 [00:06<00:08, 131.65it/s]

Running chain 1:  35%|███▍      | 581/1667 [00:06<00:08, 133.39it/s]

Running chain 5:  40%|███▉      | 664/1667 [00:06<00:06, 155.56it/s]

Running chain 0:  40%|███▉      | 664/1667 [00:06<00:06, 152.55it/s]

Running chain 4:  40%|███▉      | 664/1667 [00:06<00:06, 151.56it/s]

Running chain 2:  40%|███▉      | 664/1667 [00:06<00:06, 145.56it/s]

Running chain 3:  40%|███▉      | 664/1667 [00:06<00:06, 143.89it/s]

Running chain 5:  45%|████▍     | 747/1667 [00:06<00:05, 167.54it/s]

Running chain 1:  40%|███▉      | 664/1667 [00:06<00:07, 139.88it/s]

Running chain 0:  45%|████▍     | 747/1667 [00:07<00:05, 162.58it/s]

Running chain 4:  45%|████▍     | 747/1667 [00:07<00:05, 165.39it/s]

Running chain 3:  45%|████▍     | 747/1667 [00:07<00:05, 157.45it/s]

Running chain 2:  45%|████▍     | 747/1667 [00:07<00:05, 154.06it/s]

Running chain 5:  50%|████▉     | 830/1667 [00:07<00:04, 175.87it/s]

Running chain 1:  45%|████▍     | 747/1667 [00:07<00:06, 149.45it/s]

Running chain 0:  50%|████▉     | 830/1667 [00:07<00:04, 171.87it/s]

Running chain 4:  50%|████▉     | 830/1667 [00:07<00:04, 176.47it/s]

Running chain 3:  50%|████▉     | 830/1667 [00:07<00:04, 169.79it/s]

Running chain 5:  55%|█████▍    | 913/1667 [00:07<00:04, 184.37it/s]

Running chain 2:  50%|████▉     | 830/1667 [00:07<00:05, 164.12it/s]

Running chain 1:  50%|████▉     | 830/1667 [00:07<00:05, 160.92it/s]

Running chain 0:  55%|█████▍    | 913/1667 [00:07<00:04, 183.99it/s]

Running chain 4:  55%|█████▍    | 913/1667 [00:07<00:04, 183.60it/s]

Running chain 3:  55%|█████▍    | 913/1667 [00:08<00:04, 173.55it/s]

Running chain 2:  55%|█████▍    | 913/1667 [00:08<00:04, 175.77it/s]

Running chain 5:  60%|█████▉    | 996/1667 [00:08<00:03, 183.16it/s]

Running chain 1:  55%|█████▍    | 913/1667 [00:08<00:04, 167.65it/s]

Running chain 0:  60%|█████▉    | 996/1667 [00:08<00:03, 181.00it/s]

Running chain 4:  60%|█████▉    | 996/1667 [00:08<00:03, 167.88it/s]

Running chain 5:  65%|██████▍   | 1079/1667 [00:08<00:03, 179.79it/s]

Running chain 2:  60%|█████▉    | 996/1667 [00:08<00:04, 163.50it/s]

Running chain 3:  60%|█████▉    | 996/1667 [00:08<00:04, 158.00it/s]

Running chain 1:  60%|█████▉    | 996/1667 [00:08<00:04, 163.88it/s]

Running chain 0:  65%|██████▍   | 1079/1667 [00:08<00:03, 185.05it/s]

Running chain 5:  70%|██████▉   | 1162/1667 [00:09<00:02, 172.83it/s]

Running chain 4:  65%|██████▍   | 1079/1667 [00:09<00:03, 152.91it/s]

Running chain 0:  70%|██████▉   | 1162/1667 [00:09<00:02, 186.17it/s]

Running chain 1:  65%|██████▍   | 1079/1667 [00:09<00:03, 162.85it/s]

Running chain 2:  65%|██████▍   | 1079/1667 [00:09<00:03, 153.45it/s]

Running chain 3:  65%|██████▍   | 1079/1667 [00:09<00:04, 146.05it/s]

Running chain 5:  75%|███████▍  | 1245/1667 [00:09<00:02, 170.55it/s]

Running chain 0:  75%|███████▍  | 1245/1667 [00:09<00:02, 184.59it/s]

Running chain 4:  70%|██████▉   | 1162/1667 [00:09<00:03, 146.65it/s]

Running chain 1:  70%|██████▉   | 1162/1667 [00:09<00:03, 161.76it/s]

Running chain 2:  70%|██████▉   | 1162/1667 [00:09<00:03, 153.37it/s]

Running chain 3:  70%|██████▉   | 1162/1667 [00:10<00:03, 143.91it/s]

Running chain 0:  80%|███████▉  | 1328/1667 [00:10<00:01, 186.50it/s]

Running chain 5:  80%|███████▉  | 1328/1667 [00:10<00:01, 171.47it/s]

Running chain 1:  75%|███████▍  | 1245/1667 [00:10<00:02, 159.66it/s]

Running chain 2:  75%|███████▍  | 1245/1667 [00:10<00:02, 153.04it/s]

Running chain 4:  75%|███████▍  | 1245/1667 [00:10<00:02, 141.45it/s]

Running chain 0:  85%|████████▍ | 1411/1667 [00:10<00:01, 183.67it/s]

Running chain 3:  75%|███████▍  | 1245/1667 [00:10<00:03, 131.07it/s]

Running chain 5:  85%|████████▍ | 1411/1667 [00:10<00:01, 157.95it/s]

Running chain 1:  80%|███████▉  | 1328/1667 [00:10<00:02, 152.23it/s]

Running chain 2:  80%|███████▉  | 1328/1667 [00:11<00:02, 144.79it/s]

Running chain 0:  90%|████████▉ | 1494/1667 [00:11<00:00, 182.58it/s]

Running chain 4:  80%|███████▉  | 1328/1667 [00:11<00:02, 130.12it/s]

Running chain 5:  90%|████████▉ | 1494/1667 [00:11<00:01, 161.42it/s]

Running chain 3:  80%|███████▉  | 1328/1667 [00:11<00:02, 129.39it/s]

Running chain 0:  95%|█████████▍| 1577/1667 [00:11<00:00, 182.54it/s]

Running chain 1:  85%|████████▍ | 1411/1667 [00:11<00:01, 152.48it/s]

Running chain 2:  85%|████████▍ | 1411/1667 [00:11<00:01, 143.44it/s]

Running chain 5:  95%|█████████▍| 1577/1667 [00:11<00:00, 164.87it/s]

Running chain 4:  85%|████████▍ | 1411/1667 [00:11<00:01, 130.60it/s]

Running chain 0: 100%|█████████▉| 1660/1667 [00:11<00:00, 186.57it/s]

Running chain 0: 100%|██████████| 1667/1667 [00:11<00:00, 138.99it/s]

Running chain 1:  90%|████████▉ | 1494/1667 [00:12<00:01, 157.62it/s]

Running chain 3:  85%|████████▍ | 1411/1667 [00:12<00:01, 129.29it/s]

Running chain 2:  90%|████████▉ | 1494/1667 [00:12<00:01, 146.97it/s]

Running chain 5: 100%|█████████▉| 1660/1667 [00:12<00:00, 168.38it/s]

Running chain 5: 100%|██████████| 1667/1667 [00:12<00:00, 136.05it/s]

Running chain 4:  90%|████████▉ | 1494/1667 [00:12<00:01, 133.18it/s]

Running chain 1:  95%|█████████▍| 1577/1667 [00:12<00:00, 163.58it/s]

Running chain 3:  90%|████████▉ | 1494/1667 [00:12<00:01, 134.48it/s]

Running chain 2:  95%|█████████▍| 1577/1667 [00:12<00:00, 151.49it/s]

Running chain 1: 100%|█████████▉| 1660/1667 [00:13<00:00, 160.80it/s]

Running chain 1: 100%|██████████| 1667/1667 [00:13<00:00, 127.66it/s]

Running chain 4:  95%|█████████▍| 1577/1667 [00:13<00:00, 132.92it/s]

Running chain 2: 100%|█████████▉| 1660/1667 [00:13<00:00, 149.09it/s]

Running chain 2: 100%|██████████| 1667/1667 [00:13<00:00, 124.98it/s]

Running chain 3:  95%|█████████▍| 1577/1667 [00:13<00:00, 129.37it/s]

Running chain 4: 100%|█████████▉| 1660/1667 [00:13<00:00, 131.85it/s]

Running chain 4: 100%|██████████| 1667/1667 [00:13<00:00, 121.18it/s]

Running chain 3: 100%|█████████▉| 1660/1667 [00:13<00:00, 138.62it/s]

Running chain 3: 100%|██████████| 1667/1667 [00:13<00:00, 120.21it/s]

### 3.2 Recalibrated base + vitals
New intercept and slope for the base score, plus the vital coefficients.

$$\operatorname{logit} p_i = a + b\, s_i + v_i^\top \gamma, \qquad a \sim \mathcal{N}(0, 1),\quad b \sim \mathcal{N}(1, 1),\quad \gamma_k \sim \mathcal{N}(0, 1)$$

$$p(a, b, \gamma \mid D_\text{new}) \;\propto\; \prod_{i \in \text{new}} p_i^{y_i} (1 - p_i)^{1 - y_i} \;\cdot\; \mathcal{N}(a; 0, 1)\, \mathcal{N}(b; 1, 1) \prod_k \mathcal{N}(\gamma_k; 0, 1)$$

In [8]:
RECAL_COLS = ["base_lp"] + VITAL_COLS

with pm.Model(coords={"feature": RECAL_COLS}) as model_recal:
    intercept = pm.Normal("intercept", mu=0, sigma=1)
    # the base score's slope is centred on 1 (keep it as is); the vitals start at 0
    beta = pm.Normal("beta", mu=np.r_[1.0, np.zeros(len(VITAL_COLS))], sigma=1, dims="feature")

    pm.Bernoulli("dead", logit_p=intercept + pm.math.dot(X.loc[in_new, RECAL_COLS].values, beta),
                 observed=y_new)

    idata_recal = pm.sample(667, tune=1000, chains=6, nuts_sampler="numpyro", random_seed=SEED)

NUTS[numpyro]: [intercept, beta]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 0:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 1:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 2:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 3:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 4:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 5:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 4:   5%|▍         | 83/1667 [00:02<00:28, 54.99it/s]

Running chain 5:   5%|▍         | 83/1667 [00:02<00:34, 45.56it/s]

Running chain 3:   5%|▍         | 83/1667 [00:02<00:35, 44.17it/s]

Running chain 1:   5%|▍         | 83/1667 [00:02<00:35, 44.06it/s]

Running chain 0:   5%|▍         | 83/1667 [00:03<00:41, 38.16it/s]

Running chain 2:   5%|▍         | 83/1667 [00:03<00:43, 36.70it/s]

Running chain 4:  10%|▉         | 166/1667 [00:04<00:33, 44.16it/s]

Running chain 5:  10%|▉         | 166/1667 [00:05<00:41, 35.84it/s]

Running chain 3:  10%|▉         | 166/1667 [00:05<00:42, 35.62it/s]

Running chain 2:  10%|▉         | 166/1667 [00:05<00:42, 35.72it/s]

Running chain 1:  10%|▉         | 166/1667 [00:05<00:45, 33.35it/s]

Running chain 0:  10%|▉         | 166/1667 [00:06<00:45, 33.03it/s]

Running chain 4:  15%|█▍        | 249/1667 [00:06<00:31, 44.89it/s]

Running chain 5:  15%|█▍        | 249/1667 [00:07<00:32, 42.97it/s]

Running chain 2:  15%|█▍        | 249/1667 [00:07<00:32, 43.52it/s]

Running chain 3:  15%|█▍        | 249/1667 [00:07<00:34, 40.55it/s]

Running chain 1:  15%|█▍        | 249/1667 [00:07<00:35, 39.39it/s]

Running chain 0:  15%|█▍        | 249/1667 [00:07<00:38, 36.95it/s]

Running chain 4:  20%|█▉        | 332/1667 [00:08<00:27, 48.49it/s]

Running chain 5:  20%|█▉        | 332/1667 [00:08<00:28, 47.01it/s]

Running chain 2:  20%|█▉        | 332/1667 [00:08<00:28, 47.24it/s]

Running chain 3:  20%|█▉        | 332/1667 [00:08<00:29, 44.90it/s]

Running chain 1:  20%|█▉        | 332/1667 [00:09<00:30, 43.09it/s]

Running chain 4:  25%|██▍       | 415/1667 [00:09<00:23, 53.17it/s]

Running chain 0:  20%|█▉        | 332/1667 [00:09<00:31, 42.48it/s]

Running chain 5:  25%|██▍       | 415/1667 [00:09<00:23, 52.81it/s]

Running chain 2:  25%|██▍       | 415/1667 [00:09<00:23, 52.47it/s]

Running chain 3:  25%|██▍       | 415/1667 [00:10<00:25, 50.07it/s]

Running chain 1:  25%|██▍       | 415/1667 [00:10<00:26, 46.48it/s]

Running chain 0:  25%|██▍       | 415/1667 [00:10<00:26, 48.14it/s]

Running chain 4:  30%|██▉       | 498/1667 [00:10<00:22, 52.26it/s]

Running chain 2:  30%|██▉       | 498/1667 [00:11<00:22, 52.93it/s]

Running chain 3:  30%|██▉       | 498/1667 [00:11<00:22, 53.06it/s]

Running chain 5:  30%|██▉       | 498/1667 [00:11<00:23, 50.44it/s]

Running chain 0:  30%|██▉       | 498/1667 [00:12<00:22, 51.28it/s]

Running chain 1:  30%|██▉       | 498/1667 [00:12<00:23, 49.16it/s]

Running chain 4:  35%|███▍      | 581/1667 [00:12<00:19, 54.75it/s]

Running chain 2:  35%|███▍      | 581/1667 [00:12<00:19, 57.05it/s]

Running chain 3:  35%|███▍      | 581/1667 [00:12<00:19, 55.82it/s]

Running chain 5:  35%|███▍      | 581/1667 [00:12<00:20, 53.40it/s]

Running chain 0:  35%|███▍      | 581/1667 [00:13<00:19, 55.56it/s]

Running chain 4:  40%|███▉      | 664/1667 [00:13<00:16, 59.80it/s]

Running chain 1:  35%|███▍      | 581/1667 [00:13<00:20, 53.21it/s]

Running chain 2:  40%|███▉      | 664/1667 [00:13<00:15, 62.81it/s]

Running chain 3:  40%|███▉      | 664/1667 [00:14<00:16, 60.32it/s]

Running chain 5:  40%|███▉      | 664/1667 [00:14<00:17, 58.05it/s]

Running chain 0:  40%|███▉      | 664/1667 [00:14<00:16, 61.37it/s]

Running chain 1:  40%|███▉      | 664/1667 [00:14<00:17, 58.94it/s]

Running chain 4:  45%|████▍     | 747/1667 [00:14<00:14, 61.87it/s]

Running chain 2:  45%|████▍     | 747/1667 [00:14<00:13, 65.92it/s]

Running chain 3:  45%|████▍     | 747/1667 [00:15<00:15, 60.88it/s]

Running chain 5:  45%|████▍     | 747/1667 [00:15<00:16, 56.94it/s]

Running chain 0:  45%|████▍     | 747/1667 [00:15<00:14, 62.43it/s]

Running chain 1:  45%|████▍     | 747/1667 [00:15<00:15, 59.83it/s]

Running chain 4:  50%|████▉     | 830/1667 [00:16<00:13, 60.38it/s]

Running chain 2:  50%|████▉     | 830/1667 [00:16<00:13, 62.86it/s]

Running chain 3:  50%|████▉     | 830/1667 [00:16<00:13, 64.12it/s]

Running chain 5:  50%|████▉     | 830/1667 [00:16<00:13, 62.22it/s]

Running chain 0:  50%|████▉     | 830/1667 [00:16<00:12, 67.05it/s]

Running chain 1:  50%|████▉     | 830/1667 [00:16<00:12, 64.59it/s]

Running chain 4:  55%|█████▍    | 913/1667 [00:17<00:11, 63.81it/s]

Running chain 2:  55%|█████▍    | 913/1667 [00:17<00:11, 66.12it/s]

Running chain 3:  55%|█████▍    | 913/1667 [00:17<00:11, 68.37it/s]

Running chain 5:  55%|█████▍    | 913/1667 [00:17<00:11, 65.85it/s]

Running chain 0:  55%|█████▍    | 913/1667 [00:17<00:10, 69.20it/s]

Running chain 1:  55%|█████▍    | 913/1667 [00:17<00:10, 69.97it/s]

Running chain 4:  60%|█████▉    | 996/1667 [00:18<00:10, 62.78it/s]

Running chain 3:  60%|█████▉    | 996/1667 [00:18<00:09, 69.46it/s]

Running chain 2:  60%|█████▉    | 996/1667 [00:18<00:10, 62.10it/s]

Running chain 5:  60%|█████▉    | 996/1667 [00:19<00:11, 60.77it/s]

Running chain 0:  60%|█████▉    | 996/1667 [00:19<00:10, 63.72it/s]

Running chain 1:  60%|█████▉    | 996/1667 [00:19<00:10, 64.90it/s]

Running chain 3:  65%|██████▍   | 1079/1667 [00:19<00:08, 68.71it/s]

Running chain 2:  65%|██████▍   | 1079/1667 [00:20<00:09, 64.44it/s]

Running chain 4:  65%|██████▍   | 1079/1667 [00:20<00:09, 59.26it/s]

Running chain 1:  65%|██████▍   | 1079/1667 [00:20<00:09, 64.58it/s]

Running chain 0:  65%|██████▍   | 1079/1667 [00:20<00:09, 62.81it/s]

Running chain 5:  65%|██████▍   | 1079/1667 [00:20<00:10, 58.24it/s]

Running chain 3:  70%|██████▉   | 1162/1667 [00:21<00:07, 65.95it/s]

Running chain 2:  70%|██████▉   | 1162/1667 [00:21<00:07, 64.18it/s]

Running chain 4:  70%|██████▉   | 1162/1667 [00:21<00:08, 56.54it/s]

Running chain 1:  70%|██████▉   | 1162/1667 [00:22<00:08, 62.48it/s]

Running chain 0:  70%|██████▉   | 1162/1667 [00:22<00:08, 61.72it/s]

Running chain 5:  70%|██████▉   | 1162/1667 [00:22<00:08, 58.00it/s]

Running chain 3:  75%|███████▍  | 1245/1667 [00:22<00:06, 65.20it/s]

Running chain 2:  75%|███████▍  | 1245/1667 [00:22<00:06, 64.61it/s]

Running chain 4:  75%|███████▍  | 1245/1667 [00:23<00:07, 57.19it/s]

Running chain 0:  75%|███████▍  | 1245/1667 [00:23<00:06, 62.68it/s]

Running chain 1:  75%|███████▍  | 1245/1667 [00:23<00:06, 61.51it/s]

Running chain 2:  80%|███████▉  | 1328/1667 [00:24<00:05, 62.69it/s]

Running chain 5:  75%|███████▍  | 1245/1667 [00:24<00:07, 54.72it/s]

Running chain 3:  80%|███████▉  | 1328/1667 [00:24<00:05, 61.80it/s]

Running chain 4:  80%|███████▉  | 1328/1667 [00:24<00:06, 54.73it/s]

Running chain 0:  80%|███████▉  | 1328/1667 [00:25<00:05, 59.20it/s]

Running chain 1:  80%|███████▉  | 1328/1667 [00:25<00:05, 58.75it/s]

Running chain 3:  85%|████████▍ | 1411/1667 [00:25<00:04, 63.53it/s]

Running chain 2:  85%|████████▍ | 1411/1667 [00:25<00:04, 62.90it/s]

Running chain 5:  80%|███████▉  | 1328/1667 [00:25<00:05, 56.84it/s]

Running chain 4:  85%|████████▍ | 1411/1667 [00:26<00:04, 56.53it/s]

Running chain 0:  85%|████████▍ | 1411/1667 [00:26<00:04, 59.56it/s]

Running chain 1:  85%|████████▍ | 1411/1667 [00:26<00:04, 58.45it/s]

Running chain 2:  90%|████████▉ | 1494/1667 [00:26<00:02, 64.91it/s]

Running chain 3:  90%|████████▉ | 1494/1667 [00:26<00:02, 61.90it/s]

Running chain 5:  85%|████████▍ | 1411/1667 [00:26<00:04, 57.09it/s]

Running chain 0:  90%|████████▉ | 1494/1667 [00:27<00:02, 61.37it/s]

Running chain 4:  90%|████████▉ | 1494/1667 [00:27<00:03, 56.56it/s]

Running chain 2:  95%|█████████▍| 1577/1667 [00:27<00:01, 65.30it/s]

Running chain 1:  90%|████████▉ | 1494/1667 [00:27<00:02, 59.30it/s]

Running chain 3:  95%|█████████▍| 1577/1667 [00:28<00:01, 62.72it/s]

Running chain 5:  90%|████████▉ | 1494/1667 [00:28<00:03, 57.52it/s]

Running chain 0:  95%|█████████▍| 1577/1667 [00:28<00:01, 62.07it/s]

Running chain 2: 100%|█████████▉| 1660/1667 [00:29<00:00, 66.07it/s]

Running chain 2: 100%|██████████| 1667/1667 [00:29<00:00, 57.17it/s]

Running chain 1:  95%|█████████▍| 1577/1667 [00:29<00:01, 59.19it/s]

Running chain 4:  95%|█████████▍| 1577/1667 [00:29<00:01, 55.25it/s]

Running chain 3: 100%|█████████▉| 1660/1667 [00:29<00:00, 61.61it/s]

Running chain 3: 100%|██████████| 1667/1667 [00:29<00:00, 60.36it/s]

Running chain 3: 100%|██████████| 1667/1667 [00:29<00:00, 56.27it/s]

Running chain 5:  95%|█████████▍| 1577/1667 [00:29<00:01, 55.87it/s]

Running chain 0: 100%|█████████▉| 1660/1667 [00:30<00:00, 61.20it/s]

Running chain 0: 100%|██████████| 1667/1667 [00:30<00:00, 54.75it/s]

Running chain 1: 100%|█████████▉| 1660/1667 [00:30<00:00, 59.44it/s]

Running chain 1: 100%|██████████| 1667/1667 [00:30<00:00, 54.13it/s]

Running chain 4: 100%|█████████▉| 1660/1667 [00:30<00:00, 55.33it/s]

Running chain 4: 100%|██████████| 1667/1667 [00:30<00:00, 53.95it/s]

Running chain 5: 100%|█████████▉| 1660/1667 [00:31<00:00, 59.98it/s]

Running chain 5: 100%|██████████| 1667/1667 [00:31<00:00, 53.65it/s]

### 3.3 Old posterior as prior
Full model; the base posterior is the prior for the shared parameters, N(0, 1) for the vitals.

$$\operatorname{logit} p_i = \alpha + x_i^\top \beta + v_i^\top \gamma, \qquad (\alpha, \beta) \sim \mathcal{N}(\mu_\text{old}, \Sigma_\text{old}), \qquad \gamma_k \sim \mathcal{N}(0, 1)$$

$\mu_\text{old}, \Sigma_\text{old}$ = mean and covariance of the base posterior draws, so $\mathcal{N}(\mu_\text{old}, \Sigma_\text{old}) \approx p(\alpha, \beta \mid D_\text{old})$:

$$p(\alpha, \beta, \gamma \mid D_\text{old}, D_\text{new}) \;\propto\; \prod_{i \in \text{new}} p_i^{y_i} (1 - p_i)^{1 - y_i} \;\cdot\; \underbrace{\mathcal{N}(\alpha, \beta;\, \mu_\text{old}, \Sigma_\text{old})}_{\approx\, p(\alpha, \beta \mid D_\text{old})} \prod_k \mathcal{N}(\gamma_k; 0, 1)$$

In [9]:
# prior for the parameters the base model has: mean and covariance of its posterior draws
prev = base_draws.values                                   # intercept + BASE_COLS

with pm.Model(coords={"feature": ALL_COLS}) as model_prior:
    old = pm.MvNormal("old", mu=prev.mean(axis=0), cov=np.cov(prev, rowvar=False))
    added = pm.Normal("added", mu=0, sigma=1, shape=len(VITAL_COLS))
    intercept = pm.Deterministic("intercept", old[0])
    beta = pm.Deterministic("beta", pm.math.concatenate([old[1:], added]), dims="feature")

    pm.Bernoulli("dead", logit_p=intercept + pm.math.dot(X.loc[in_new, ALL_COLS].values, beta),
                 observed=y_new)

    idata_prior = pm.sample(667, tune=1000, chains=6, nuts_sampler="numpyro", random_seed=SEED)

NUTS[numpyro]: [old, added]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 0:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 1:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 2:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 3:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 4:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 5:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 0:   5%|▍         | 83/1667 [00:03<00:41, 37.89it/s]

Running chain 2:   5%|▍         | 83/1667 [00:03<00:45, 35.03it/s]

Running chain 1:   5%|▍         | 83/1667 [00:03<00:47, 33.30it/s]

Running chain 5:   5%|▍         | 83/1667 [00:03<00:49, 31.95it/s]

Running chain 4:   5%|▍         | 83/1667 [00:03<00:51, 30.60it/s]

Running chain 3:   5%|▍         | 83/1667 [00:03<00:53, 29.80it/s]

Running chain 1:  10%|▉         | 166/1667 [00:05<00:41, 36.27it/s]

Running chain 2:  10%|▉         | 166/1667 [00:05<00:43, 34.61it/s]

Running chain 5:  10%|▉         | 166/1667 [00:05<00:43, 34.87it/s]

Running chain 0:  10%|▉         | 166/1667 [00:05<00:44, 33.71it/s]

Running chain 4:  10%|▉         | 166/1667 [00:06<00:45, 33.24it/s]

Running chain 3:  10%|▉         | 166/1667 [00:06<00:51, 29.25it/s]

Running chain 1:  15%|█▍        | 249/1667 [00:06<00:29, 47.77it/s]

Running chain 0:  15%|█▍        | 249/1667 [00:06<00:30, 46.62it/s]

Running chain 5:  15%|█▍        | 249/1667 [00:06<00:30, 46.65it/s]

Running chain 2:  15%|█▍        | 249/1667 [00:07<00:31, 45.54it/s]

Running chain 4:  15%|█▍        | 249/1667 [00:07<00:32, 43.86it/s]

Running chain 3:  15%|█▍        | 249/1667 [00:07<00:34, 41.47it/s]

Running chain 1:  20%|█▉        | 332/1667 [00:07<00:23, 57.59it/s]

Running chain 0:  20%|█▉        | 332/1667 [00:07<00:23, 55.78it/s]

Running chain 2:  20%|█▉        | 332/1667 [00:08<00:25, 52.68it/s]

Running chain 5:  20%|█▉        | 332/1667 [00:08<00:25, 53.01it/s]

Running chain 4:  20%|█▉        | 332/1667 [00:08<00:24, 53.70it/s]

Running chain 1:  25%|██▍       | 415/1667 [00:08<00:18, 68.44it/s]

Running chain 0:  25%|██▍       | 415/1667 [00:08<00:18, 67.17it/s]

Running chain 3:  20%|█▉        | 332/1667 [00:08<00:27, 48.99it/s]

Running chain 5:  25%|██▍       | 415/1667 [00:09<00:19, 62.83it/s]

Running chain 2:  25%|██▍       | 415/1667 [00:09<00:20, 62.30it/s]

Running chain 4:  25%|██▍       | 415/1667 [00:09<00:20, 62.20it/s]

Running chain 1:  30%|██▉       | 498/1667 [00:09<00:15, 73.82it/s]

Running chain 0:  30%|██▉       | 498/1667 [00:09<00:16, 69.83it/s]

Running chain 3:  25%|██▍       | 415/1667 [00:09<00:21, 59.22it/s]

Running chain 4:  30%|██▉       | 498/1667 [00:10<00:16, 69.87it/s]

Running chain 2:  30%|██▉       | 498/1667 [00:10<00:17, 65.98it/s]

Running chain 5:  30%|██▉       | 498/1667 [00:10<00:17, 66.03it/s]

Running chain 1:  35%|███▍      | 581/1667 [00:10<00:13, 77.94it/s]

Running chain 0:  35%|███▍      | 581/1667 [00:10<00:14, 74.77it/s]

Running chain 3:  30%|██▉       | 498/1667 [00:10<00:18, 64.14it/s]

Running chain 4:  35%|███▍      | 581/1667 [00:11<00:14, 76.36it/s]

Running chain 2:  35%|███▍      | 581/1667 [00:11<00:14, 73.07it/s]

Running chain 5:  35%|███▍      | 581/1667 [00:11<00:15, 71.25it/s]

Running chain 1:  40%|███▉      | 664/1667 [00:11<00:11, 85.33it/s]

Running chain 0:  40%|███▉      | 664/1667 [00:11<00:12, 82.43it/s]

Running chain 2:  40%|███▉      | 664/1667 [00:11<00:12, 82.80it/s]

Running chain 4:  40%|███▉      | 664/1667 [00:11<00:11, 84.24it/s]

Running chain 3:  35%|███▍      | 581/1667 [00:11<00:15, 70.28it/s]

Running chain 1:  45%|████▍     | 747/1667 [00:12<00:09, 93.05it/s]

Running chain 5:  40%|███▉      | 664/1667 [00:12<00:12, 78.97it/s]

Running chain 0:  45%|████▍     | 747/1667 [00:12<00:10, 89.32it/s]

Running chain 2:  45%|████▍     | 747/1667 [00:12<00:10, 89.98it/s]

Running chain 4:  45%|████▍     | 747/1667 [00:12<00:10, 90.37it/s]

Running chain 1:  50%|████▉     | 830/1667 [00:12<00:08, 100.74it/s]

Running chain 3:  40%|███▉      | 664/1667 [00:12<00:12, 78.24it/s]

Running chain 5:  45%|████▍     | 747/1667 [00:12<00:10, 86.82it/s]

Running chain 0:  50%|████▉     | 830/1667 [00:13<00:08, 94.26it/s]

Running chain 4:  50%|████▉     | 830/1667 [00:13<00:08, 96.89it/s]

Running chain 2:  50%|████▉     | 830/1667 [00:13<00:08, 93.18it/s]

Running chain 1:  55%|█████▍    | 913/1667 [00:13<00:07, 103.65it/s]

Running chain 3:  45%|████▍     | 747/1667 [00:13<00:10, 85.12it/s]

Running chain 5:  50%|████▉     | 830/1667 [00:13<00:09, 91.91it/s]

Running chain 0:  55%|█████▍    | 913/1667 [00:13<00:07, 101.35it/s]

Running chain 4:  55%|█████▍    | 913/1667 [00:14<00:07, 97.77it/s]

Running chain 2:  55%|█████▍    | 913/1667 [00:14<00:08, 92.91it/s]

Running chain 3:  50%|████▉     | 830/1667 [00:14<00:10, 80.81it/s]

Running chain 5:  55%|█████▍    | 913/1667 [00:14<00:08, 86.45it/s]

Running chain 1:  60%|█████▉    | 996/1667 [00:14<00:07, 86.17it/s]

Running chain 0:  60%|█████▉    | 996/1667 [00:15<00:07, 85.43it/s]

Running chain 2:  60%|█████▉    | 996/1667 [00:15<00:07, 88.27it/s]

Running chain 4:  60%|█████▉    | 996/1667 [00:15<00:07, 87.13it/s]

Running chain 3:  55%|█████▍    | 913/1667 [00:15<00:08, 86.83it/s]

Running chain 1:  65%|██████▍   | 1079/1667 [00:15<00:06, 87.81it/s]

Running chain 5:  60%|█████▉    | 996/1667 [00:15<00:07, 85.10it/s]

Running chain 0:  65%|██████▍   | 1079/1667 [00:16<00:07, 83.09it/s]

Running chain 4:  65%|██████▍   | 1079/1667 [00:16<00:06, 88.61it/s]

Running chain 2:  65%|██████▍   | 1079/1667 [00:16<00:06, 87.38it/s]

Running chain 3:  60%|█████▉    | 996/1667 [00:16<00:07, 86.63it/s]

Running chain 1:  70%|██████▉   | 1162/1667 [00:16<00:05, 89.69it/s]

Running chain 5:  65%|██████▍   | 1079/1667 [00:16<00:06, 85.27it/s]

Running chain 0:  70%|██████▉   | 1162/1667 [00:17<00:05, 84.55it/s]

Running chain 4:  70%|██████▉   | 1162/1667 [00:17<00:05, 89.51it/s]

Running chain 2:  70%|██████▉   | 1162/1667 [00:17<00:05, 88.00it/s]

Running chain 3:  65%|██████▍   | 1079/1667 [00:17<00:06, 86.06it/s]

Running chain 1:  75%|███████▍  | 1245/1667 [00:17<00:04, 92.06it/s]

Running chain 5:  70%|██████▉   | 1162/1667 [00:17<00:05, 84.93it/s]

Running chain 4:  75%|███████▍  | 1245/1667 [00:18<00:04, 89.74it/s]

Running chain 0:  75%|███████▍  | 1245/1667 [00:18<00:05, 82.98it/s]

Running chain 2:  75%|███████▍  | 1245/1667 [00:18<00:04, 87.97it/s]

Running chain 1:  80%|███████▉  | 1328/1667 [00:18<00:03, 92.72it/s]

Running chain 3:  70%|██████▉   | 1162/1667 [00:18<00:05, 86.77it/s]

Running chain 5:  75%|███████▍  | 1245/1667 [00:18<00:04, 84.60it/s]

Running chain 4:  80%|███████▉  | 1328/1667 [00:19<00:03, 88.74it/s]

Running chain 2:  80%|███████▉  | 1328/1667 [00:19<00:03, 89.30it/s]

Running chain 1:  85%|████████▍ | 1411/1667 [00:19<00:02, 92.85it/s]

Running chain 0:  80%|███████▉  | 1328/1667 [00:19<00:04, 82.54it/s]

Running chain 3:  75%|███████▍  | 1245/1667 [00:19<00:04, 87.42it/s]

Running chain 5:  80%|███████▉  | 1328/1667 [00:19<00:03, 84.84it/s]

Running chain 4:  85%|████████▍ | 1411/1667 [00:20<00:02, 87.95it/s]

Running chain 1:  90%|████████▉ | 1494/1667 [00:20<00:01, 93.69it/s]

Running chain 2:  85%|████████▍ | 1411/1667 [00:20<00:02, 87.65it/s]

Running chain 0:  85%|████████▍ | 1411/1667 [00:20<00:03, 82.16it/s]

Running chain 3:  80%|███████▉  | 1328/1667 [00:20<00:03, 87.47it/s]

Running chain 5:  85%|████████▍ | 1411/1667 [00:20<00:03, 84.06it/s]

Running chain 1:  95%|█████████▍| 1577/1667 [00:20<00:00, 95.63it/s]

Running chain 4:  90%|████████▉ | 1494/1667 [00:20<00:01, 88.72it/s]

Running chain 2:  90%|████████▉ | 1494/1667 [00:21<00:01, 88.08it/s]

Running chain 3:  85%|████████▍ | 1411/1667 [00:21<00:02, 88.69it/s]

Running chain 0:  90%|████████▉ | 1494/1667 [00:21<00:02, 81.90it/s]

Running chain 5:  90%|████████▉ | 1494/1667 [00:21<00:02, 83.86it/s]

Running chain 1: 100%|█████████▉| 1660/1667 [00:21<00:00, 96.50it/s]

Running chain 1: 100%|██████████| 1667/1667 [00:21<00:00, 76.60it/s]

Running chain 4:  95%|█████████▍| 1577/1667 [00:21<00:01, 88.01it/s]

Running chain 2:  95%|█████████▍| 1577/1667 [00:21<00:01, 88.68it/s]

Running chain 3:  90%|████████▉ | 1494/1667 [00:22<00:01, 89.33it/s]

Running chain 0:  95%|█████████▍| 1577/1667 [00:22<00:01, 83.27it/s]

Running chain 5:  95%|█████████▍| 1577/1667 [00:22<00:01, 85.71it/s]

Running chain 4: 100%|█████████▉| 1660/1667 [00:22<00:00, 89.99it/s]

Running chain 2: 100%|█████████▉| 1660/1667 [00:22<00:00, 90.37it/s]

Running chain 4: 100%|██████████| 1667/1667 [00:22<00:00, 73.05it/s]

Running chain 2: 100%|██████████| 1667/1667 [00:22<00:00, 72.84it/s]

Running chain 3:  95%|█████████▍| 1577/1667 [00:22<00:00, 90.07it/s]

Running chain 0: 100%|█████████▉| 1660/1667 [00:23<00:00, 86.71it/s]

Running chain 0: 100%|██████████| 1667/1667 [00:23<00:00, 72.19it/s]

Running chain 5: 100%|█████████▉| 1660/1667 [00:23<00:00, 90.54it/s]

Running chain 5: 100%|██████████| 1667/1667 [00:23<00:00, 71.36it/s]

Running chain 3: 100%|█████████▉| 1660/1667 [00:23<00:00, 100.40it/s]

Running chain 3: 100%|██████████| 1667/1667 [00:23<00:00, 70.77it/s]

### 3.4 New data only (reference)
Full model from scratch on the new 10K, ignoring the base model.

$$\operatorname{logit} p_i = \alpha + x_i^\top \beta + v_i^\top \gamma, \qquad \alpha,\ \beta_j,\ \gamma_k \sim \mathcal{N}(0, 1)$$

$$p(\alpha, \beta, \gamma \mid D_\text{new}) \;\propto\; \prod_{i \in \text{new}} p_i^{y_i} (1 - p_i)^{1 - y_i} \;\cdot\; \mathcal{N}(\alpha; 0, 1) \prod_j \mathcal{N}(\beta_j; 0, 1) \prod_k \mathcal{N}(\gamma_k; 0, 1)$$

In [10]:
with pm.Model(coords={"feature": ALL_COLS}) as model_new:
    intercept = pm.Normal("intercept", mu=0, sigma=1)
    beta = pm.Normal("beta", mu=0, sigma=1, dims="feature")

    pm.Bernoulli("dead", logit_p=intercept + pm.math.dot(X.loc[in_new, ALL_COLS].values, beta),
                 observed=y_new)

    idata_new = pm.sample(667, tune=1000, chains=6, nuts_sampler="numpyro", random_seed=SEED)

NUTS[numpyro]: [intercept, beta]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 0:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 1:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 2:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 3:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 4:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 5:   0%|          | 0/1667 [00:01<?, ?it/s]

Running chain 5:   5%|▍         | 83/1667 [00:03<00:53, 29.74it/s]

Running chain 4:   5%|▍         | 83/1667 [00:04<00:58, 27.01it/s]

Running chain 0:   5%|▍         | 83/1667 [00:04<01:00, 26.35it/s]

Running chain 3:   5%|▍         | 83/1667 [00:04<01:08, 23.13it/s]

Running chain 2:   5%|▍         | 83/1667 [00:04<01:11, 22.05it/s]

Running chain 1:   5%|▍         | 83/1667 [00:04<01:12, 21.75it/s]

Running chain 5:  10%|▉         | 166/1667 [00:06<00:50, 29.75it/s]

Running chain 4:  10%|▉         | 166/1667 [00:06<00:49, 30.04it/s]

Running chain 1:  10%|▉         | 166/1667 [00:06<00:48, 30.80it/s]

Running chain 3:  10%|▉         | 166/1667 [00:06<00:51, 29.41it/s]

Running chain 0:  10%|▉         | 166/1667 [00:06<00:52, 28.57it/s]

Running chain 2:  10%|▉         | 166/1667 [00:07<00:53, 28.07it/s]

Running chain 1:  15%|█▍        | 249/1667 [00:07<00:33, 42.39it/s]

Running chain 5:  15%|█▍        | 249/1667 [00:07<00:35, 39.98it/s]

Running chain 4:  15%|█▍        | 249/1667 [00:07<00:35, 39.94it/s]

Running chain 0:  15%|█▍        | 249/1667 [00:08<00:36, 38.78it/s]

Running chain 3:  15%|█▍        | 249/1667 [00:08<00:36, 38.96it/s]

Running chain 2:  15%|█▍        | 249/1667 [00:08<00:36, 38.49it/s]

Running chain 1:  20%|█▉        | 332/1667 [00:08<00:25, 52.63it/s]

Running chain 5:  20%|█▉        | 332/1667 [00:09<00:27, 48.10it/s]

Running chain 4:  20%|█▉        | 332/1667 [00:09<00:27, 48.38it/s]

Running chain 0:  20%|█▉        | 332/1667 [00:09<00:27, 47.86it/s]

Running chain 3:  20%|█▉        | 332/1667 [00:09<00:28, 47.12it/s]

Running chain 2:  20%|█▉        | 332/1667 [00:09<00:28, 46.62it/s]

Running chain 1:  25%|██▍       | 415/1667 [00:09<00:19, 63.38it/s]

Running chain 5:  25%|██▍       | 415/1667 [00:09<00:21, 59.41it/s]

Running chain 4:  25%|██▍       | 415/1667 [00:10<00:21, 58.62it/s]

Running chain 0:  25%|██▍       | 415/1667 [00:10<00:21, 57.10it/s]

Running chain 3:  25%|██▍       | 415/1667 [00:10<00:21, 56.92it/s]

Running chain 2:  25%|██▍       | 415/1667 [00:10<00:22, 56.50it/s]

Running chain 1:  30%|██▉       | 498/1667 [00:10<00:17, 67.11it/s]

Running chain 5:  30%|██▉       | 498/1667 [00:11<00:18, 63.44it/s]

Running chain 4:  30%|██▉       | 498/1667 [00:11<00:18, 64.74it/s]

Running chain 3:  30%|██▉       | 498/1667 [00:11<00:17, 65.48it/s]

Running chain 0:  30%|██▉       | 498/1667 [00:11<00:18, 63.00it/s]

Running chain 2:  30%|██▉       | 498/1667 [00:11<00:18, 62.70it/s]

Running chain 1:  35%|███▍      | 581/1667 [00:11<00:15, 72.05it/s]

Running chain 5:  35%|███▍      | 581/1667 [00:11<00:15, 70.09it/s]

Running chain 4:  35%|███▍      | 581/1667 [00:11<00:15, 71.13it/s]

Running chain 0:  35%|███▍      | 581/1667 [00:12<00:15, 70.90it/s]

Running chain 3:  35%|███▍      | 581/1667 [00:12<00:15, 72.07it/s]

Running chain 2:  35%|███▍      | 581/1667 [00:12<00:15, 69.14it/s]

Running chain 1:  40%|███▉      | 664/1667 [00:12<00:12, 78.92it/s]

Running chain 4:  40%|███▉      | 664/1667 [00:12<00:12, 80.29it/s]

Running chain 5:  40%|███▉      | 664/1667 [00:12<00:12, 78.57it/s]

Running chain 0:  40%|███▉      | 664/1667 [00:12<00:12, 80.63it/s]

Running chain 3:  40%|███▉      | 664/1667 [00:13<00:12, 79.38it/s]

Running chain 1:  45%|████▍     | 747/1667 [00:13<00:10, 87.44it/s]

Running chain 2:  40%|███▉      | 664/1667 [00:13<00:13, 76.25it/s]

Running chain 4:  45%|████▍     | 747/1667 [00:13<00:10, 86.54it/s]

Running chain 5:  45%|████▍     | 747/1667 [00:13<00:10, 85.60it/s]

Running chain 0:  45%|████▍     | 747/1667 [00:13<00:10, 88.51it/s]

Running chain 3:  45%|████▍     | 747/1667 [00:13<00:10, 85.66it/s]

Running chain 1:  50%|████▉     | 830/1667 [00:14<00:08, 93.43it/s]

Running chain 2:  45%|████▍     | 747/1667 [00:14<00:10, 84.63it/s]

Running chain 4:  50%|████▉     | 830/1667 [00:14<00:09, 91.46it/s]

Running chain 5:  50%|████▉     | 830/1667 [00:14<00:09, 91.04it/s]

Running chain 0:  50%|████▉     | 830/1667 [00:14<00:09, 92.35it/s]

Running chain 3:  50%|████▉     | 830/1667 [00:14<00:08, 93.75it/s]

Running chain 1:  55%|█████▍    | 913/1667 [00:14<00:07, 98.70it/s]

Running chain 2:  50%|████▉     | 830/1667 [00:14<00:09, 90.62it/s]

Running chain 5:  55%|█████▍    | 913/1667 [00:14<00:07, 97.93it/s]

Running chain 4:  55%|█████▍    | 913/1667 [00:15<00:07, 96.59it/s]

Running chain 0:  55%|█████▍    | 913/1667 [00:15<00:07, 100.21it/s]

Running chain 3:  55%|█████▍    | 913/1667 [00:15<00:07, 98.88it/s]

Running chain 2:  55%|█████▍    | 913/1667 [00:15<00:07, 95.82it/s]

Running chain 5:  60%|█████▉    | 996/1667 [00:15<00:06, 96.99it/s]

Running chain 1:  60%|█████▉    | 996/1667 [00:15<00:07, 91.19it/s]

Running chain 0:  60%|█████▉    | 996/1667 [00:15<00:06, 99.60it/s]

Running chain 4:  60%|█████▉    | 996/1667 [00:15<00:07, 93.48it/s]

Running chain 3:  60%|█████▉    | 996/1667 [00:16<00:06, 97.21it/s]

Running chain 2:  60%|█████▉    | 996/1667 [00:16<00:07, 93.37it/s]

Running chain 1:  65%|██████▍   | 1079/1667 [00:16<00:06, 90.35it/s]

Running chain 0:  65%|██████▍   | 1079/1667 [00:16<00:06, 96.26it/s]

Running chain 3:  65%|██████▍   | 1079/1667 [00:16<00:05, 99.41it/s]

Running chain 5:  65%|██████▍   | 1079/1667 [00:16<00:06, 90.60it/s]

Running chain 4:  65%|██████▍   | 1079/1667 [00:16<00:06, 90.84it/s]

Running chain 2:  65%|██████▍   | 1079/1667 [00:17<00:06, 90.84it/s]

Running chain 3:  70%|██████▉   | 1162/1667 [00:17<00:05, 97.31it/s]

Running chain 0:  70%|██████▉   | 1162/1667 [00:17<00:05, 94.26it/s]

Running chain 1:  70%|██████▉   | 1162/1667 [00:17<00:05, 88.49it/s]

Running chain 5:  70%|██████▉   | 1162/1667 [00:17<00:05, 89.01it/s]

Running chain 4:  70%|██████▉   | 1162/1667 [00:17<00:05, 88.82it/s]

Running chain 2:  70%|██████▉   | 1162/1667 [00:18<00:05, 87.66it/s]

Running chain 3:  75%|███████▍  | 1245/1667 [00:18<00:04, 97.05it/s]

Running chain 0:  75%|███████▍  | 1245/1667 [00:18<00:04, 94.20it/s]

Running chain 1:  75%|███████▍  | 1245/1667 [00:18<00:04, 87.78it/s]

Running chain 4:  75%|███████▍  | 1245/1667 [00:18<00:04, 87.91it/s]

Running chain 5:  75%|███████▍  | 1245/1667 [00:18<00:04, 85.05it/s]

Running chain 3:  80%|███████▉  | 1328/1667 [00:19<00:03, 96.77it/s]

Running chain 0:  80%|███████▉  | 1328/1667 [00:19<00:03, 93.69it/s]

Running chain 2:  75%|███████▍  | 1245/1667 [00:19<00:04, 85.36it/s]

Running chain 1:  80%|███████▉  | 1328/1667 [00:19<00:03, 87.34it/s]

Running chain 4:  80%|███████▉  | 1328/1667 [00:19<00:03, 86.22it/s]

Running chain 5:  80%|███████▉  | 1328/1667 [00:20<00:04, 82.89it/s]

Running chain 3:  85%|████████▍ | 1411/1667 [00:20<00:02, 97.35it/s]

Running chain 0:  85%|████████▍ | 1411/1667 [00:20<00:02, 92.20it/s]

Running chain 2:  80%|███████▉  | 1328/1667 [00:20<00:03, 85.03it/s]

Running chain 1:  85%|████████▍ | 1411/1667 [00:20<00:02, 88.21it/s]

Running chain 4:  85%|████████▍ | 1411/1667 [00:20<00:02, 86.54it/s]

Running chain 5:  85%|████████▍ | 1411/1667 [00:21<00:03, 81.37it/s]

Running chain 3:  90%|████████▉ | 1494/1667 [00:21<00:01, 95.69it/s]

Running chain 0:  90%|████████▉ | 1494/1667 [00:21<00:01, 91.73it/s]

Running chain 1:  90%|████████▉ | 1494/1667 [00:21<00:01, 89.18it/s]

Running chain 2:  85%|████████▍ | 1411/1667 [00:21<00:03, 83.79it/s]

Running chain 4:  90%|████████▉ | 1494/1667 [00:21<00:01, 87.42it/s]

Running chain 5:  90%|████████▉ | 1494/1667 [00:22<00:02, 80.11it/s]

Running chain 3:  95%|█████████▍| 1577/1667 [00:22<00:00, 94.55it/s]

Running chain 0:  95%|█████████▍| 1577/1667 [00:22<00:00, 91.35it/s]

Running chain 1:  95%|█████████▍| 1577/1667 [00:22<00:01, 87.77it/s]

Running chain 2:  90%|████████▉ | 1494/1667 [00:22<00:02, 82.52it/s]

Running chain 4:  95%|█████████▍| 1577/1667 [00:22<00:01, 86.33it/s]

Running chain 3: 100%|█████████▉| 1660/1667 [00:23<00:00, 93.37it/s]

Running chain 3: 100%|██████████| 1667/1667 [00:23<00:00, 71.98it/s]

Running chain 5:  95%|█████████▍| 1577/1667 [00:23<00:01, 80.35it/s]

Running chain 0: 100%|█████████▉| 1660/1667 [00:23<00:00, 91.15it/s]

Running chain 0: 100%|██████████| 1667/1667 [00:23<00:00, 71.35it/s]

Running chain 1: 100%|█████████▉| 1660/1667 [00:23<00:00, 87.61it/s]

Running chain 1: 100%|██████████| 1667/1667 [00:23<00:00, 70.70it/s]

Running chain 2:  95%|█████████▍| 1577/1667 [00:23<00:01, 84.07it/s]

Running chain 4: 100%|█████████▉| 1660/1667 [00:23<00:00, 88.30it/s]

Running chain 4: 100%|██████████| 1667/1667 [00:23<00:00, 70.25it/s]

Running chain 5: 100%|█████████▉| 1660/1667 [00:23<00:00, 87.08it/s]

Running chain 5: 100%|██████████| 1667/1667 [00:24<00:00, 69.44it/s]

Running chain 2: 100%|█████████▉| 1660/1667 [00:24<00:00, 94.88it/s]

Running chain 2: 100%|██████████| 1667/1667 [00:24<00:00, 68.64it/s]

### 3.5 Joint model with imputed vitals (reference, needs the old records)
All old + new patients in one full model. The old patients' vitals are unknown, so their risk is averaged over the vitals model.

$z_i$ = the three standardised vitals, $v(z_i) = (z_{i1}, z_{i1}^2, z_{i2}, z_{i2}^2, z_{i3}, z_{i3}^2)$, observed for new patients only.

$$\operatorname{logit} p_i = \alpha + x_i^\top \beta + v(z_i)^\top \gamma, \qquad z_i \sim \mathcal{N}(\nu_0 + B^\top x_i,\; L L^\top)$$

$$p(\alpha, \beta, \gamma, \nu_0, B, L \mid D_{\text{old}}, D_{\text{new}}) \;\propto\; \prod_{i \in \text{new}} p_i^{y_i} (1 - p_i)^{1 - y_i}\, \mathcal{N}(z_i;\, \nu_0 + B^\top x_i,\, L L^\top) \;\cdot\; \prod_{i \in \text{old}} \bar p_i^{\,y_i} (1 - \bar p_i)^{1 - y_i} \;\cdot\; \text{priors}$$

$$\bar p_i = \int \sigma\!\left(\alpha + x_i^\top \beta + v(z)^\top \gamma\right) \mathcal{N}(z;\, \nu_0 + B^\top x_i,\, L L^\top)\, dz \;\approx\; \sum_{k=1}^{125} w_k\, \sigma\!\left(\alpha + x_i^\top \beta + v(\nu_0 + B^\top x_i + L e_k)^\top \gamma\right)$$

Gauss–Hermite grid: 5 points per vital, 125 points $e_k$ with weights $w_k$. $\bar p_i$ depends only on $x_i$, so identical old patients are collapsed into one row with a count.

In [11]:
from numpy.polynomial.hermite_e import hermegauss

# an old patient's likelihood depends only on the base features (the vitals are averaged out),
# so identical old patients are collapsed into one row with a count, as in demo_adv
old = (X.loc[in_old, BASE_COLS].assign(dead=df.loc[in_old, "dead"])
         .groupby(BASE_COLS, as_index=False).agg(n=("dead", "size"), dead=("dead", "sum")))
Xb_old, n_old, d_old = old[BASE_COLS].values, old["n"].values, old["dead"].values
Xb_new = X.loc[in_new, BASE_COLS].values
Z_new = X.loc[in_new, VITALS].values                 # standardised vitals, observed for the new patients only

# Gauss–Hermite grid for averaging over a 3D standard normal: 5 points per vital, 125 points e_k with weights w_k
nodes, weights = hermegauss(5)
E = np.stack(np.meshgrid(nodes, nodes, nodes, indexing="ij"), axis=-1).reshape(-1, 3)
W = np.stack(np.meshgrid(weights, weights, weights, indexing="ij"), axis=-1).reshape(-1, 3).prod(axis=1)
log_w = np.log(W / W.sum())

with pm.Model(coords={"feature": ALL_COLS}) as model_joint:
    # vitals model, learned where the vitals are observed: z ~ N(nu0 + x·B, L·Lᵀ)
    nu0 = pm.Normal("nu0", mu=0, sigma=1, shape=3)
    B = pm.Normal("B", mu=0, sigma=1, shape=(len(BASE_COLS), 3))
    chol, _, _ = pm.LKJCholeskyCov("chol", n=3, eta=2, sd_dist=pm.Exponential.dist(1.0, shape=3))
    pm.MvNormal("z_new", mu=nu0 + pm.math.dot(Xb_new, B), chol=chol, observed=Z_new)

    # outcome model: the same full model for every patient
    intercept = pm.Normal("intercept", mu=0, sigma=1)
    beta = pm.Normal("beta", mu=0, sigma=1, dims="feature")

    # new patients: vitals observed
    pm.Bernoulli("dead_new", logit_p=intercept + pm.math.dot(X.loc[in_new, ALL_COLS].values, beta), observed=y_new)

    # old patients: average the risk over their unknown vitals, z = nu0 + x·B + L·e_k at every grid point
    z = (nu0 + pm.math.dot(Xb_old, B))[:, None, :] + pm.math.dot(E, chol.T)[None, :, :]       # rows × 125 × 3
    g = beta[len(BASE_COLS):]                                                                 # V1, V1², V2, V2², V3, V3²
    eta = ((intercept + pm.math.dot(Xb_old, beta[:len(BASE_COLS)]))[:, None]
           + g[0] * z[..., 0] + g[1] * z[..., 0] ** 2
           + g[2] * z[..., 1] + g[3] * z[..., 1] ** 2
           + g[4] * z[..., 2] + g[5] * z[..., 2] ** 2)
    log_p1 = pm.math.logsumexp(log_w - pm.math.log1pexp(-eta), axis=1, keepdims=False)    # log P(death | x)
    log_p0 = pm.math.logsumexp(log_w - pm.math.log1pexp(eta), axis=1, keepdims=False)     # log P(survival | x)
    pm.Potential("dead_old", pm.math.sum(d_old * log_p1 + (n_old - d_old) * log_p0))      # binomial, per row

    # dense mass matrix: lets NUTS learn the correlations between the vitals model and the outcome model
    idata_joint = pm.sample(667, tune=1000, chains=6, nuts_sampler="numpyro", random_seed=SEED,
                            nuts={"dense_mass": True})

NUTS[numpyro]: [nu0, B, chol, intercept, beta]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

  0%|          | 0/1667 [00:00<?, ?it/s]

Compiling.. :   0%|          | 0/1667 [00:00<?, ?it/s]

Running chain 0:   0%|          | 0/1667 [00:02<?, ?it/s]

Running chain 1:   0%|          | 0/1667 [00:02<?, ?it/s]

Running chain 2:   0%|          | 0/1667 [00:02<?, ?it/s]

Running chain 3:   0%|          | 0/1667 [00:02<?, ?it/s]

Running chain 4:   0%|          | 0/1667 [00:02<?, ?it/s]

Running chain 5:   0%|          | 0/1667 [00:02<?, ?it/s]

Running chain 4:   5%|▍         | 83/1667 [00:53<16:21,  1.61it/s]

Running chain 2:   5%|▍         | 83/1667 [00:54<16:30,  1.60it/s]

Running chain 5:   5%|▍         | 83/1667 [00:55<16:52,  1.56it/s]

Running chain 0:   5%|▍         | 83/1667 [01:02<19:10,  1.38it/s]

Running chain 3:   5%|▍         | 83/1667 [01:12<22:11,  1.19it/s]

Running chain 1:   5%|▍         | 83/1667 [01:19<24:39,  1.07it/s]

Running chain 4:  10%|▉         | 166/1667 [02:00<18:13,  1.37it/s]

Running chain 5:  10%|▉         | 166/1667 [02:02<18:31,  1.35it/s]

Running chain 2:  10%|▉         | 166/1667 [02:07<19:26,  1.29it/s]

Running chain 0:  10%|▉         | 166/1667 [02:12<19:51,  1.26it/s]

Running chain 3:  10%|▉         | 166/1667 [02:23<21:18,  1.17it/s]

Running chain 1:  10%|▉         | 166/1667 [02:27<21:35,  1.16it/s]

Running chain 4:  15%|█▍        | 249/1667 [02:30<13:10,  1.79it/s]

Running chain 5:  15%|█▍        | 249/1667 [02:31<13:16,  1.78it/s]

Running chain 2:  15%|█▍        | 249/1667 [02:33<13:22,  1.77it/s]

Running chain 0:  15%|█▍        | 249/1667 [02:38<13:35,  1.74it/s]

Running chain 5:  20%|█▉        | 332/1667 [02:51<09:38,  2.31it/s]

Running chain 3:  15%|█▍        | 249/1667 [02:52<14:38,  1.61it/s]

Running chain 2:  20%|█▉        | 332/1667 [02:53<09:39,  2.30it/s]

Running chain 4:  20%|█▉        | 332/1667 [02:53<10:01,  2.22it/s]

Running chain 1:  15%|█▍        | 249/1667 [02:55<14:44,  1.60it/s]

Running chain 0:  20%|█▉        | 332/1667 [02:57<09:47,  2.27it/s]

Running chain 5:  25%|██▍       | 415/1667 [03:07<07:15,  2.87it/s]

Running chain 2:  25%|██▍       | 415/1667 [03:09<07:18,  2.86it/s]

Running chain 4:  25%|██▍       | 415/1667 [03:12<07:40,  2.72it/s]

Running chain 3:  20%|█▉        | 332/1667 [03:13<10:35,  2.10it/s]

Running chain 1:  20%|█▉        | 332/1667 [03:14<10:27,  2.13it/s]

Running chain 0:  25%|██▍       | 415/1667 [03:15<07:28,  2.79it/s]

Running chain 5:  30%|██▉       | 498/1667 [03:25<05:52,  3.32it/s]

Running chain 2:  30%|██▉       | 498/1667 [03:26<05:49,  3.35it/s]

Running chain 3:  25%|██▍       | 415/1667 [03:29<07:49,  2.67it/s]

Running chain 4:  30%|██▉       | 498/1667 [03:30<06:13,  3.13it/s]

Running chain 1:  25%|██▍       | 415/1667 [03:32<07:50,  2.66it/s]

Running chain 0:  30%|██▉       | 498/1667 [03:33<06:02,  3.22it/s]

Running chain 2:  35%|███▍      | 581/1667 [03:40<04:41,  3.86it/s]

Running chain 5:  35%|███▍      | 581/1667 [03:41<04:50,  3.74it/s]

Running chain 4:  35%|███▍      | 581/1667 [03:46<04:59,  3.62it/s]

Running chain 3:  30%|██▉       | 498/1667 [03:46<06:10,  3.16it/s]

Running chain 1:  30%|██▉       | 498/1667 [03:49<06:11,  3.15it/s]

Running chain 0:  35%|███▍      | 581/1667 [03:50<04:58,  3.64it/s]

Running chain 2:  40%|███▉      | 664/1667 [03:54<03:50,  4.36it/s]

Running chain 5:  40%|███▉      | 664/1667 [03:55<03:56,  4.23it/s]

Running chain 4:  40%|███▉      | 664/1667 [04:00<04:02,  4.13it/s]

Running chain 3:  35%|███▍      | 581/1667 [04:00<04:53,  3.70it/s]

Running chain 0:  40%|███▉      | 664/1667 [04:04<04:01,  4.16it/s]

Running chain 1:  35%|███▍      | 581/1667 [04:04<04:58,  3.63it/s]

Running chain 2:  45%|████▍     | 747/1667 [04:07<03:10,  4.82it/s]

Running chain 5:  45%|████▍     | 747/1667 [04:08<03:14,  4.74it/s]

Running chain 4:  45%|████▍     | 747/1667 [04:13<03:18,  4.63it/s]

Running chain 3:  40%|███▉      | 664/1667 [04:13<03:55,  4.26it/s]

Running chain 0:  45%|████▍     | 747/1667 [04:18<03:21,  4.57it/s]

Running chain 1:  40%|███▉      | 664/1667 [04:20<04:07,  4.05it/s]

Running chain 2:  50%|████▉     | 830/1667 [04:20<02:40,  5.23it/s]

Running chain 5:  50%|████▉     | 830/1667 [04:21<02:41,  5.19it/s]

Running chain 4:  50%|████▉     | 830/1667 [04:25<02:42,  5.14it/s]

Running chain 3:  45%|████▍     | 747/1667 [04:26<03:12,  4.78it/s]

Running chain 0:  50%|████▉     | 830/1667 [04:30<02:43,  5.11it/s]

Running chain 1:  45%|████▍     | 747/1667 [04:33<03:20,  4.60it/s]

Running chain 2:  55%|█████▍    | 913/1667 [04:33<02:16,  5.54it/s]

Running chain 5:  55%|█████▍    | 913/1667 [04:33<02:16,  5.54it/s]

Running chain 4:  55%|█████▍    | 913/1667 [04:38<02:16,  5.53it/s]

Running chain 3:  50%|████▉     | 830/1667 [04:39<02:39,  5.24it/s]

Running chain 0:  55%|█████▍    | 913/1667 [04:43<02:18,  5.45it/s]

Running chain 1:  50%|████▉     | 830/1667 [04:45<02:44,  5.10it/s]

Running chain 2:  60%|█████▉    | 996/1667 [04:48<02:00,  5.57it/s]

Running chain 5:  60%|█████▉    | 996/1667 [04:48<02:00,  5.58it/s]

Running chain 3:  55%|█████▍    | 913/1667 [04:51<02:14,  5.62it/s]

Running chain 4:  60%|█████▉    | 996/1667 [04:53<02:01,  5.54it/s]

Running chain 0:  60%|█████▉    | 996/1667 [04:57<02:00,  5.59it/s]

Running chain 1:  55%|█████▍    | 913/1667 [04:58<02:19,  5.42it/s]

Running chain 5:  65%|██████▍   | 1079/1667 [04:59<01:38,  6.00it/s]

Running chain 2:  65%|██████▍   | 1079/1667 [05:02<01:43,  5.70it/s]

Running chain 4:  65%|██████▍   | 1079/1667 [05:04<01:38,  5.95it/s]

Running chain 3:  60%|█████▉    | 996/1667 [05:06<01:59,  5.62it/s]

Running chain 0:  65%|██████▍   | 1079/1667 [05:09<01:39,  5.92it/s]

Running chain 5:  70%|██████▉   | 1162/1667 [05:11<01:19,  6.33it/s]

Running chain 1:  60%|█████▉    | 996/1667 [05:14<02:04,  5.37it/s]

Running chain 2:  70%|██████▉   | 1162/1667 [05:15<01:26,  5.81it/s]

Running chain 4:  70%|██████▉   | 1162/1667 [05:16<01:20,  6.27it/s]

Running chain 3:  65%|██████▍   | 1079/1667 [05:18<01:39,  5.93it/s]

Running chain 0:  70%|██████▉   | 1162/1667 [05:20<01:20,  6.25it/s]

Running chain 5:  75%|███████▍  | 1245/1667 [05:22<01:04,  6.57it/s]

Running chain 1:  65%|██████▍   | 1079/1667 [05:26<01:43,  5.71it/s]

Running chain 4:  75%|███████▍  | 1245/1667 [05:27<01:04,  6.54it/s]

Running chain 2:  75%|███████▍  | 1245/1667 [05:29<01:12,  5.86it/s]

Running chain 3:  70%|██████▉   | 1162/1667 [05:29<01:20,  6.28it/s]

Running chain 0:  75%|███████▍  | 1245/1667 [05:33<01:05,  6.42it/s]

Running chain 5:  80%|███████▉  | 1328/1667 [05:34<00:50,  6.73it/s]

Running chain 1:  70%|██████▉   | 1162/1667 [05:38<01:24,  6.00it/s]

Running chain 4:  80%|███████▉  | 1328/1667 [05:39<00:50,  6.72it/s]

Running chain 3:  75%|███████▍  | 1245/1667 [05:41<01:04,  6.54it/s]

Running chain 2:  80%|███████▉  | 1328/1667 [05:42<00:55,  6.08it/s]

Running chain 0:  80%|███████▉  | 1328/1667 [05:44<00:51,  6.59it/s]

Running chain 5:  85%|████████▍ | 1411/1667 [05:46<00:37,  6.88it/s]

Running chain 4:  85%|████████▍ | 1411/1667 [05:50<00:37,  6.87it/s]

Running chain 1:  75%|███████▍  | 1245/1667 [05:51<01:08,  6.13it/s]

Running chain 3:  80%|███████▉  | 1328/1667 [05:53<00:50,  6.71it/s]

Running chain 2:  85%|████████▍ | 1411/1667 [05:55<00:41,  6.19it/s]

Running chain 0:  85%|████████▍ | 1411/1667 [05:56<00:37,  6.75it/s]

Running chain 5:  90%|████████▉ | 1494/1667 [05:57<00:24,  6.97it/s]

Running chain 4:  90%|████████▉ | 1494/1667 [06:02<00:24,  6.96it/s]

Running chain 1:  80%|███████▉  | 1328/1667 [06:03<00:53,  6.34it/s]

Running chain 3:  85%|████████▍ | 1411/1667 [06:04<00:37,  6.83it/s]

Running chain 0:  90%|████████▉ | 1494/1667 [06:08<00:25,  6.85it/s]

Running chain 5:  95%|█████████▍| 1577/1667 [06:08<00:12,  7.06it/s]

Running chain 2:  90%|████████▉ | 1494/1667 [06:09<00:28,  6.11it/s]

Running chain 4:  95%|█████████▍| 1577/1667 [06:14<00:12,  6.97it/s]

Running chain 1:  85%|████████▍ | 1411/1667 [06:16<00:39,  6.43it/s]

Running chain 3:  90%|████████▉ | 1494/1667 [06:16<00:25,  6.90it/s]

Running chain 0:  95%|█████████▍| 1577/1667 [06:19<00:13,  6.90it/s]

Running chain 5: 100%|█████████▉| 1660/1667 [06:20<00:00,  7.10it/s]

Running chain 5: 100%|██████████| 1667/1667 [06:21<00:00,  7.12it/s]

Running chain 5: 100%|██████████| 1667/1667 [06:21<00:00,  4.37it/s]

Running chain 2:  95%|█████████▍| 1577/1667 [06:23<00:14,  6.05it/s]

Running chain 4: 100%|█████████▉| 1660/1667 [06:24<00:00,  7.16it/s]

Running chain 4: 100%|██████████| 1667/1667 [06:25<00:00,  7.20it/s]

Running chain 4: 100%|██████████| 1667/1667 [06:25<00:00,  4.32it/s]

Running chain 3:  95%|█████████▍| 1577/1667 [06:26<00:12,  7.22it/s]

Running chain 1:  90%|████████▉ | 1494/1667 [06:27<00:25,  6.72it/s]

Running chain 0: 100%|█████████▉| 1660/1667 [06:28<00:00,  7.48it/s]

Running chain 0: 100%|██████████| 1667/1667 [06:29<00:00,  7.56it/s]

Running chain 0: 100%|██████████| 1667/1667 [06:29<00:00,  4.28it/s]

Running chain 2: 100%|█████████▉| 1660/1667 [06:31<00:01,  6.91it/s]

Running chain 2: 100%|██████████| 1667/1667 [06:31<00:00,  7.05it/s]

Running chain 2: 100%|██████████| 1667/1667 [06:31<00:00,  4.26it/s]

Running chain 3: 100%|█████████▉| 1660/1667 [06:32<00:00,  8.48it/s]

Running chain 3: 100%|██████████| 1667/1667 [06:32<00:00,  8.67it/s]

Running chain 3: 100%|██████████| 1667/1667 [06:32<00:00,  4.24it/s]

Running chain 1:  95%|█████████▍| 1577/1667 [06:32<00:11,  8.06it/s]

Running chain 1: 100%|█████████▉| 1660/1667 [06:34<00:00, 10.59it/s]

Running chain 1: 100%|██████████| 1667/1667 [06:35<00:00, 10.89it/s]

Running chain 1: 100%|██████████| 1667/1667 [06:35<00:00,  4.22it/s]

## 4. Evaluation
All models on the same 10K test patients.

### 4.1 Scores

In [12]:
X_test = X[in_test]
y_test = df.loc[in_test, "dead"].values
p_true_test = p_true[in_test].values

def predict(d):
    """Posterior mean P(death) per test patient; d = draws with an intercept column and one column per feature."""
    cols = list(d.columns[1:])
    Xt = X_test[cols].values
    a, b = d["intercept"].values, d[cols].values
    p_sum = np.zeros(len(Xt))
    for s in range(0, len(a), 250):                      # in chunks of draws to save memory
        p_sum += (1 / (1 + np.exp(-(a[s:s + 250, None] + b[s:s + 250] @ Xt.T)))).sum(axis=0)
    return p_sum / len(a)

def auc(y, p):
    """Probability that a random death gets a higher prediction than a random survivor."""
    r = pd.Series(p).rank().values
    n1, n0 = y.sum(), len(y) - y.sum()
    return (r[y == 1].sum() - n1 * (n1 + 1) / 2) / (n1 * n0)

def scores(p):
    return {
        "AUC": auc(y_test, p),
        "Brier": np.mean((p - y_test) ** 2),
        "log loss": -np.mean(y_test * np.log(p) + (1 - y_test) * np.log(1 - p)),
        "mean |p - p_true|": np.abs(p - p_true_test).mean(),
    }

models = {
    "base (old data, no vitals)": base_draws,
    "fixed base + vitals": draws_of(idata_fixed, VITAL_COLS, base_lp=1.0),
    "recalibrated base + vitals": draws_of(idata_recal, RECAL_COLS),
    "old posterior as prior": draws_of(idata_prior, ALL_COLS),
    "new data only": draws_of(idata_new, ALL_COLS),
    "joint, imputed vitals": draws_of(idata_joint, ALL_COLS),
}
results = pd.DataFrame({name: scores(predict(d)) for name, d in models.items()}).T
results.loc["true probabilities"] = scores(p_true_test)
print(f"test patients: {len(y_test)}, deaths: {y_test.sum()}")
results.round(4)

test patients: 20000, deaths: 569

                               AUC   Brier  log loss  mean |p - p_true|
base (old data, no vitals)  0.7050  0.0271    0.1215             0.0122
fixed base + vitals         0.7509  0.0265    0.1167             0.0074
recalibrated base + vitals  0.7526  0.0264    0.1158             0.0039
old posterior as prior      0.7540  0.0264    0.1161             0.0053
new data only               0.7560  0.0264    0.1156             0.0031
joint, imputed vitals       0.7555  0.0264    0.1156             0.0030
true probabilities          0.7593  0.0263    0.1152             0.0000